"""empty message

Revision ID: 15dc4e1121d8
Revises: 048f79c9a9b4
Create Date: 2024-04-10 13:00:17.879994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dc4e1121d8'
down_revision = '048f79c9a9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
